# Generated by Django 5.2.7 on 2025-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_supplier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
