# Generated by Django 5.2.7 on 2025-11-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_supplier_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='products_supplied',
            field=models.JSONField(default=list),
        ),
    ]
