# Generated by Django 5.2.7 on 2025-11-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('IN STOCK', 'In Stock'), ('LOW STOCK', 'Low Stock'), ('OUT OF STOCK', 'Out of Stock')], default='IN STOCK', max_length=20),
        ),
    ]
