# Generated by Django 5.2.7 on 2025-11-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0008_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
